### ISSUE TITLE
Removing Double-periods

### ISSUE THREAD

**Issue by djrrb** [ninastoessinger/Suffixer#1]
It seems that replacing suffixes will leave periods in the glyph name if I start with more than one. 
Also, if my glyph name has acquired two periods, I'm not able to remove the extra period using suffixer.

Example workflow: 
- In RoboFont, I copy 'zero.lnum' and it automatically pastes as 'zero.lnum.copy_1'
- I use suffixer to add suffix 'tab' to glyph, replacing 'lnum.copy_1'
- The glyph is now named 'three..tab'
- I use suffixer again to rename '.tab' to 'tab', to remove that extra period
- Suffixer tells me there's no point, but gives me a smile anyway. :)

I encounter this a bunch and would love to deal with it more smoothly. Thoughts? 

Thanks! I ❤ Suffixer.

![screen shot 2015-05-31 at 5 23 49 pm](https://cloud.githubusercontent.com/assets/6578861/7915236/1d68eb46-0831-11e5-98c0-c05b0b3de755.png)

**Comment by ninastoessinger** [comment]
Thanks David. I’ve just uploaded v1.1 that fixes the problem you describe (i.e. the part that initially causes the double periods to appear).
As for not being able to use Suffixer to get rid of the double periods, I did for now keep the behavior that periods entered into those fields are basically ignored – I’m a bit worried about the potential for making messes otherwise – but maybe I’m trying to make this too smart...
